import type { Metadata } from "next";
import { Inter } from "next/font/google";

// global styles
import "./styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PepperMint - The World's Coolest NFT Marketplace!",
  description: "Generated by create next app",
  authors: [
    {
      name: 'Syed Vilayat Ali Rizvi',
      url: 'https://www.github.com/vilayat-ali',
    }
  ],
  keywords: [
    'NFT',
    'GenZ',
    'Free NFT Minting',
    'Next.js 14',
    'Syed Vilayat Ali Rizvi',
    'Solana',
    'Anchor Framework',
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
